services:
  - type: web
    name: indian-language-translator-api
    env: python
    buildCommand: ""
    startCommand: python backend/app.py
    envVars:
      - key: PORT
        value: 5000
    plan: free
