services:
  - type: web
    name: indian-language-translator-backend
    env: python
    region: oregon
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "python backend/app.py"
    plan: free
